# Generated by Django 5.1 on 2024-11-10 00:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto_app', '0001_initial'),
        ('Usuario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista_de_pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaentrega', models.DateTimeField()),
                ('direccion', models.CharField(max_length=40)),
                ('descuento', models.FloatField()),
                ('estado', models.CharField(max_length=25)),
                ('total', models.IntegerField()),
                ('productos', models.ManyToManyField(related_name='pedidos', through='Pedido_app.lista_de_pedidos', to='Producto_app.producto')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_tomados', to='Usuario_app.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_realizados', to='Usuario_app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='lista_de_pedidos',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido_app.pedido'),
        ),
    ]
