# Generated by Django 5.1 on 2024-11-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario_app', '0002_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='NOTRUT', max_length=10),
        ),
    ]
