# Generated by Django 5.1 on 2024-11-08 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogo_app', '0001_initial'),
        ('Sucursal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='producto-imagenes/')),
                ('estado', models.CharField(default='Desactivado', max_length=20)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_set', to='Catalogo_app.catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto_app.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sucursal_app.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='sucursales',
            field=models.ManyToManyField(through='Producto_app.ProductoSucursal', to='Sucursal_app.sucursal'),
        ),
    ]
