# Generated by Django 5.1 on 2024-11-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto_app', '0002_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosucursal',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
