# Generated by Django 5.1 on 2024-11-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto_app', '0003_productosucursal_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosucursal',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
