# Generated by Django 5.1 on 2024-11-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
