# Generated by Django 5.1 on 2024-11-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=70)),
                ('fono', models.CharField(max_length=15)),
                ('imagen', models.ImageField(default='200x200.png', upload_to='sucursal_imagenes/')),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
        ),
    ]
